requirements:
  - control-interface-service/requirements.txt
  - message-sender/requirements.txt
  - scheduler/requirements.txt
  - stage-based-messaging/requirements.txt
  - auth-api/requirements.txt
  - control-interface/requirements.txt
  - identity-store/requirements.txt
  - service-rating/requirements.txt
