version: '2'
services:
  seed-stage-based-messaging:
    build: .
    ports:
      - 8000:8000
    environment:
      - STAGE_BASED_MESSAGING_DATABASE=postgres://stage-based-messaging:secret@postgres/stage-based-messaging
    links:
      - seed-postgres:postgres

  stage-based-messaging-celery:
    build: .
    command: ["celery", "worker", "--app", "seed_stage_based_messaging", "--concurrency", "4", "--loglevel", "info", "-Q", "seed_stage_based_messaging"]
    environment:
      - STAGE_BASED_MESSAGING_DATABASE=postgres://stage-based-messaging:secret@postgres/stage-based-messaging
      - BROKER_URL=amqp://stage-based-messaging:secret@rabbitmq:5672/stage-based-messaging
    links:
      - seed-postgres:postgres
      - seed-rabbitmq:rabbitmq

  stage-based-messaging-celery-metrics:
    build: .
    command: ["celery", "worker", "--app", "seed_stage_based_messaging", "--concurrency", "1", "--loglevel", "info", "-Q", "priority,mediumpriority,metrics,celery"]
    environment:
      - STAGE_BASED_MESSAGING_DATABASE=postgres://stage-based-messaging:secret@postgres/stage-based-messaging
      - BROKER_URL=amqp://stage-based-messaging:secret@rabbitmq:5672/stage-based-messaging
    links:
      - seed-postgres:postgres
      - seed-rabbitmq:rabbitmq

  seed-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=stage-based-messaging
      - POSTGRES_USER=stage-based-messaging
      - POSTGRES_PASSWORD=secret
  seed-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=stage-based-messaging
      - RABBITMQ_DEFAULT_USER=stage-based-messaging
      - RABBITMQ_DEFAULT_PASS=secret
