version: '2'
services:
  message-sender:
    image: praekeltfoundation/seed-message-sender
    build: .
    ports:
      - '8000'
    environment:
      - MESSAGE_SENDER_DATABASE=postgres://message-sender:secret@postgres/message-sender
      - BROKER_URL=amqp://message-sender:secret@rabbitmq:5672/message-sender

  # Copied Celery config from MomConnect setup as of 09/03/17
  message-sender-celery:
    extends:
      service: message-sender
    command: [celery, worker, --app, seed_message_sender, -Q, 'seed_message_sender,priority,mediumpriority,celery', --concurrency, '1', --without-gossip, --without-mingle, --without-heartbeat, --loglevel, info]

  message-sender-celery-metrics:
    extends:
      service: message-sender
    command: [celery, worker, --app, seed_message_sender, -Q, metrics, --concurrency, '1', --without-gossip, --without-mingle, --without-heartbeat, --loglevel, info]

  message-sender-celery-send:
    extends:
      service: message-sender
    command: [celery, worker, --app, seed_message_sender, -Q, lowpriority, --concurrency, '1', --without-gossip, --without-mingle, --without-heartbeat, --loglevel, info]

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=message-sender
      - POSTGRES_USER=message-sender
      - POSTGRES_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=message-sender
      - RABBITMQ_DEFAULT_USER=message-sender
      - RABBITMQ_DEFAULT_PASS=secret
